=== bioinformaticsdotca/RDM_To-2605/module3_tutorial/8_additional_challenges/8_1_required_object/work/schema.json
{
    "$id": "https://example.com/person.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Person",
    "type": "object",
    "required": [
      "firstName",
      "lastName",
      "icd10",
      "occupation"
    ],
    "properties": {
      "firstName": {
        "type": "string",
        "description": "The person's first name."
      },
      "lastName": {
        "type": "string",
        "description": "The person's last name.",
        "pattern": "[A-Za-z- ]+"
      },
      "age": {
        "description": "Age in years which must be equal to or greater than zero.",
        "type": "integer",
        "minimum": 0
      },
      "icd10": {
        "description": "Identification of a disease, condition, or injury based on signs, symptoms, medical history, and physical exams. Using ICD10 codes",
        "type": "string"
      },
      "occupation":{},
      "honorific": {
        "enum": [
          "Mr",
          "Miss",
          "Mrs",
          "Mx"
        ]
      },
      "country": {
        "enum": [
          "USA",
          "Canada"
        ]
      },
      "province/territory/state": {
        "type": "string"
      }
    },
    "if": {
      "properties": {
        "country": {
          "enum": [
            "USA"
          ]
        }
      }
    },
    "then": {
      "required": [
        "province/territory/state"
      ],
      "properties": {
        "province/territory/state": {
          "enum": [
            "Wisconsin",
            "Virginia",
            "Dakota"
          ]
        }
      }
    },
    "else": {
      "required": [
        "province/territory/state"
      ],
      "properties": {
        "province/territory/state": {
          "enum": [
            "Quebec",
            "Ontario",
            "Vancouver"
          ]
        }
      }
    }
  }

=== bioinformaticsdotca/RDM_To-2605/module3_tutorial/8_additional_challenges/8_1_required_object/work/example.json
{
    "$schema":"./schema.json",
    "firstName": "Marguerite",
    "lastName": "Tremblay",
    "age": 34,
    "icd10": "J45.5",
    "honorific": "Mrs",
    "country": "Canada",
    "province/territory/state": "Quebec",
    "occupation":{
        "name" : "Bioinformatician",
        "field" : ["Chemistry","Biology","Programming"]
    }
  }
